#!/usr/bin/env python3
"""Regenerate FindACrib/Models/States.swift from findacrib.com/states/index.json.

The state maps' names, centres and spans come from build_lihtc_states.py's
index, so the app's table and the files on the server cannot drift apart.

    python3 scripts/gen_states.py            # reads the live index
    python3 scripts/gen_states.py path.json  # or a local one
"""
import json
import sys
import urllib.request
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "FindACrib" / "Models" / "States.swift"
src = sys.argv[1] if len(sys.argv) > 1 else "https://findacrib.com/states/index.json"
if src.startswith("http"):
    idx = json.load(urllib.request.urlopen(urllib.request.Request(src, headers={"User-Agent": "findacrib gen_states"}), timeout=30))
else:
    idx = json.load(open(src))
rows = sorted(idx["states"].items(), key=lambda kv: kv[1]["name"])
lines = []
for st, s in rows:
    name = "New York State" if st == "NY" else s["name"]
    lines.append(f'        .state("{st}", "{name}", lat: {s["lat"]}, lng: {s["lng"]}, span: {min(s["span"], 12)}),')
OUT.write_text(f'''import Foundation

// GENERATED by scripts/gen_states.py from findacrib.com/states/index.json —
// edit build_lihtc_states.py or the generator, not this file.

extension City {{
    /// Every state's income-restricted buildings (owner, 2026-09-24: "State
    /// picker + map"), from HUD's Low-Income Housing Tax Credit database. See
    /// build_lihtc_states.py and `City.state(_:_:lat:lng:span:)`.
    static let states: [City] = [
{chr(10).join(lines)}
    ]
}}
''')
print(f"wrote {len(rows)} states -> {OUT}")
