import Foundation

// GENERATED by scripts/gen_states.py from findacrib.com/states/index.json —
// edit build_lihtc_states.py or the generator, not this file.

extension City {
    /// Every state's income-restricted buildings (owner, 2026-09-24: "State
    /// picker + map"), from HUD's Low-Income Housing Tax Credit database. See
    /// build_lihtc_states.py and `City.state(_:_:lat:lng:span:)`.
    static let states: [City] = [
        .state("AL", "Alabama", lat: 32.6323, lng: -86.691, span: 5.097),
        .state("AK", "Alaska", lat: 60.0956, lng: -148.5749, span: 12),
        .state("AZ", "Arizona", lat: 33.2878, lng: -112.1022, span: 4.433),
        .state("AR", "Arkansas", lat: 34.8139, lng: -92.2733, span: 3.693),
        .state("CA", "California", lat: 36.2236, lng: -119.4584, span: 8.096),
        .state("CO", "Colorado", lat: 38.9292, lng: -106.1679, span: 4.084),
        .state("CT", "Connecticut", lat: 41.4827, lng: -72.8071, span: 1.291),
        .state("DE", "Delaware", lat: 39.1211, lng: -75.4367, span: 1.515),
        .state("DC", "District of Columbia", lat: 38.8959, lng: -76.9828, span: 0.23),
        .state("FL", "Florida", lat: 28.0603, lng: -83.5995, span: 6.062),
        .state("GA", "Georgia", lat: 32.8172, lng: -83.1481, span: 4.586),
        .state("HI", "Hawaii", lat: 20.8233, lng: -157.273, span: 3.786),
        .state("ID", "Idaho", lat: 45.4151, lng: -114.3952, span: 6.597),
        .state("IL", "Illinois", lat: 40.1914, lng: -89.0939, span: 5.038),
        .state("IN", "Indiana", lat: 39.8282, lng: -86.2235, span: 4.27),
        .state("IA", "Iowa", lat: 42.0226, lng: -93.4533, span: 5.097),
        .state("KS", "Kansas", lat: 38.4288, lng: -97.7878, span: 5.432),
        .state("KY", "Kentucky", lat: 37.8843, lng: -85.6779, span: 5.093),
        .state("LA", "Louisiana", lat: 31.2863, lng: -91.8794, span: 3.463),
        .state("ME", "Maine", lat: 44.9921, lng: -69.3059, span: 3.88),
        .state("MD", "Maryland", lat: 38.9416, lng: -77.3588, span: 3.108),
        .state("MA", "Massachusetts", lat: 42.1797, lng: -71.6248, span: 1.936),
        .state("MI", "Michigan", lat: 43.8666, lng: -84.6604, span: 4.562),
        .state("MN", "Minnesota", lat: 45.8502, lng: -94.2027, span: 5.006),
        .state("MS", "Mississippi", lat: 32.6222, lng: -89.7341, span: 5.264),
        .state("MO", "Missouri", lat: 38.3433, lng: -92.2331, span: 4.48),
        .state("MT", "Montana", lat: 46.9434, lng: -109.7979, span: 8.767),
        .state("NE", "Nebraska", lat: 41.3234, lng: -99.7527, span: 6.724),
        .state("NV", "Nevada", lat: 38.4792, lng: -117.1242, span: 5.71),
        .state("NH", "New Hampshire", lat: 43.6115, lng: -71.5927, span: 1.981),
        .state("NJ", "New Jersey", lat: 40.1478, lng: -74.6187, span: 1.792),
        .state("NM", "New Mexico", lat: 34.3658, lng: -105.9436, span: 5.425),
        .state("NY", "New York State", lat: 41.9827, lng: -76.2401, span: 4.55),
        .state("NC", "North Carolina", lat: 35.3341, lng: -79.7444, span: 4.851),
        .state("ND", "North Dakota", lat: 47.3818, lng: -100.2051, span: 5.897),
        .state("OH", "Ohio", lat: 40.2831, lng: -82.6113, span: 3.362),
        .state("OK", "Oklahoma", lat: 35.3897, lng: -97.1306, span: 4.322),
        .state("OR", "Oregon", lat: 44.0592, lng: -121.0953, span: 5.24),
        .state("PA", "Pennsylvania", lat: 40.8954, lng: -77.6922, span: 4.492),
        .state("PR", "Puerto Rico", lat: 18.2352, lng: -66.5117, span: 1.101),
        .state("RI", "Rhode Island", lat: 41.7179, lng: -71.478, span: 0.67),
        .state("SC", "South Carolina", lat: 33.7269, lng: -80.8743, span: 3.289),
        .state("SD", "South Dakota", lat: 44.1218, lng: -100.1893, span: 6.237),
        .state("TN", "Tennessee", lat: 35.7847, lng: -86.1947, span: 6.668),
        .state("TX", "Texas", lat: 30.4827, lng: -100.2694, span: 10.618),
        .state("UT", "Utah", lat: 39.4165, lng: -111.5565, span: 5.293),
        .state("VT", "Vermont", lat: 43.8964, lng: -72.6471, span: 2.414),
        .state("VA", "Virginia", lat: 37.8315, lng: -79.1585, span: 5.187),
        .state("WA", "Washington", lat: 47.2148, lng: -120.3118, span: 5.327),
        .state("WV", "West Virginia", lat: 38.7224, lng: -80.167, span: 4.008),
        .state("WI", "Wisconsin", lat: 44.5545, lng: -90.1499, span: 4.563),
        .state("WY", "Wyoming", lat: 42.9551, lng: -107.8565, span: 5.377),
    ]
}
