#!/usr/bin/env python3
"""Regenerate the inline App Store QR code in index.html.

The QR lives INLINE in the page rather than as an /app-qr.svg file on purpose:
the shell already ships as one document, a separate asset would need its own
line in scripts/deploy_app.sh (and its own cache-bust on every change), and an
inline path costs one gzipped kilobyte against a request plus a round trip.

Run it whenever APP_URL changes:

    ~/.venvs/dhcr-map/bin/python scripts/make_app_qr.py

It rewrites the <path> between the QR-PATH markers in index.html and prints the
module count. build_city_pages.py copies the shell, so the city pages pick the
new code up on the next deploy without anything else to remember.
"""
import re
import sys
from pathlib import Path

import segno

ROOT = Path(__file__).resolve().parent.parent
APP_URL = 'https://apps.apple.com/us/app/find-a-crib/id6807549249'

# Error level M (15%) rather than L: the code is printed at ~200 px on screen
# and people scan it off a laptop at an angle, through a phone camera that is
# also fighting the display's own refresh. L saves four modules and nothing
# else. H would push it to 37 modules and make each one smaller, which is the
# wrong trade at this display size.
ERROR = 'm'


def qr_path(url: str):
    """Return (svg path data, module count) for the QR of `url`.

    Each row is emitted as horizontal runs rather than one rect per module,
    which is what keeps the path near 4 KB instead of 12 KB.
    """
    matrix = [list(row) for row in segno.make(url, error=ERROR).matrix]
    n = len(matrix)
    parts = []
    for y, row in enumerate(matrix):
        x = 0
        while x < n:
            if not row[x]:
                x += 1
                continue
            w = 1
            while x + w < n and row[x + w]:
                w += 1
            parts.append(f'M{x} {y}h{w}v1h-{w}z')
            x += w
    return ''.join(parts), n


def main() -> int:
    d, n = qr_path(APP_URL)
    page = ROOT / 'index.html'
    html = page.read_text()
    block = (
        f'<!-- QR-PATH: generated by scripts/make_app_qr.py from {APP_URL} — do not hand-edit -->\n'
        f'        <svg class="qr-code" viewBox="0 0 {n} {n}" role="img" '
        f'aria-label="QR code linking to Find A Crib on the App Store">'
        f'<path d="{d}" fill="#000"/></svg>\n'
        f'        <!-- /QR-PATH -->'
    )
    new, count = re.subn(
        r'<!-- QR-PATH:.*?<!-- /QR-PATH -->',
        lambda _: block,
        html,
        flags=re.S,
    )
    if count != 1:
        print(f'error: expected 1 QR-PATH block in index.html, found {count}', file=sys.stderr)
        return 1
    if new == html:
        print(f'QR unchanged ({n}x{n} modules)')
        return 0
    page.write_text(new)
    print(f'QR rewritten: {n}x{n} modules, {len(d)} chars of path -> {APP_URL}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
