import Foundation

/// The top of Search shows eight of a city's landmarks, drawn at random from
/// these fifty every time the screen appears (owner, 2026-09-22: "the top 50
/// nyc landmarks rotating randomly on these images on refresh — do the same
/// for the other cities too"). It replaced a list of neighborhood corners.
///
/// Each point is on the STREET in front of the landmark, not its centroid:
/// the tile is an Apple Look Around panorama, and Look Around only exists
/// where Apple's car or backpack went. A landmark with no panorama nearby
/// (an island, a park interior) falls back to a map snapshot of the spot in
/// ImageService, so it costs a plain tile, never a blank one.
extension HeroSpot {
    static let landmarks: [String: [HeroSpot]] = [
        "nyc": [
            HeroSpot(id: "lm-nyc-times-sq",        name: "Times Square",                    lat: 40.7580, lng: -73.9855),
            HeroSpot(id: "lm-nyc-empire-state",    name: "Empire State Building",           lat: 40.7484, lng: -73.9857),
            HeroSpot(id: "lm-nyc-chrysler",        name: "Chrysler Building",               lat: 40.7516, lng: -73.9755),
            HeroSpot(id: "lm-nyc-flatiron",        name: "Flatiron Building",               lat: 40.7411, lng: -73.9897),
            HeroSpot(id: "lm-nyc-grand-central",   name: "Grand Central Terminal",          lat: 40.7527, lng: -73.9772),
            HeroSpot(id: "lm-nyc-rockefeller",     name: "Rockefeller Center",              lat: 40.7587, lng: -73.9787),
            HeroSpot(id: "lm-nyc-st-patricks",     name: "St. Patrick's Cathedral",         lat: 40.7585, lng: -73.9763),
            HeroSpot(id: "lm-nyc-nypl",            name: "New York Public Library",         lat: 40.7532, lng: -73.9822),
            HeroSpot(id: "lm-nyc-bryant-park",     name: "Bryant Park",                     lat: 40.7536, lng: -73.9832),
            HeroSpot(id: "lm-nyc-one-wtc",         name: "One World Trade Center",          lat: 40.7127, lng: -74.0134),
            HeroSpot(id: "lm-nyc-oculus",          name: "The Oculus",                      lat: 40.7116, lng: -74.0115),
            HeroSpot(id: "lm-nyc-charging-bull",   name: "Charging Bull",                   lat: 40.7056, lng: -74.0134),
            HeroSpot(id: "lm-nyc-wall-st",         name: "Wall Street",                     lat: 40.7066, lng: -74.0090),
            HeroSpot(id: "lm-nyc-city-hall",       name: "City Hall",                       lat: 40.7127, lng: -74.0059),
            HeroSpot(id: "lm-nyc-woolworth",       name: "Woolworth Building",              lat: 40.7124, lng: -74.0083),
            HeroSpot(id: "lm-nyc-brooklyn-bridge", name: "Brooklyn Bridge",                 lat: 40.7033, lng: -73.9937),
            HeroSpot(id: "lm-nyc-dumbo",           name: "DUMBO & the Manhattan Bridge",    lat: 40.7033, lng: -73.9897),
            HeroSpot(id: "lm-nyc-washington-sq",   name: "Washington Square Arch",          lat: 40.7314, lng: -73.9971),
            HeroSpot(id: "lm-nyc-high-line",       name: "The High Line",                   lat: 40.7480, lng: -74.0048),
            HeroSpot(id: "lm-nyc-vessel",          name: "The Vessel, Hudson Yards",        lat: 40.7537, lng: -74.0020),
            HeroSpot(id: "lm-nyc-chelsea-market",  name: "Chelsea Market",                  lat: 40.7424, lng: -74.0061),
            HeroSpot(id: "lm-nyc-madison-sq-gdn",  name: "Madison Square Garden",           lat: 40.7505, lng: -73.9934),
            HeroSpot(id: "lm-nyc-macys",           name: "Macy's Herald Square",            lat: 40.7507, lng: -73.9892),
            HeroSpot(id: "lm-nyc-un",              name: "United Nations",                  lat: 40.7496, lng: -73.9680),
            HeroSpot(id: "lm-nyc-plaza",           name: "The Plaza Hotel",                 lat: 40.7645, lng: -73.9742),
            HeroSpot(id: "lm-nyc-central-park-s",  name: "Central Park South",              lat: 40.7662, lng: -73.9776),
            HeroSpot(id: "lm-nyc-columbus-circle", name: "Columbus Circle",                 lat: 40.7681, lng: -73.9819),
            HeroSpot(id: "lm-nyc-lincoln-center",  name: "Lincoln Center",                  lat: 40.7725, lng: -73.9835),
            HeroSpot(id: "lm-nyc-dakota",          name: "The Dakota",                      lat: 40.7763, lng: -73.9761),
            HeroSpot(id: "lm-nyc-natural-history", name: "American Museum of Natural History", lat: 40.7813, lng: -73.9740),
            HeroSpot(id: "lm-nyc-the-met",         name: "The Metropolitan Museum of Art",  lat: 40.7794, lng: -73.9632),
            HeroSpot(id: "lm-nyc-guggenheim",      name: "The Guggenheim",                  lat: 40.7829, lng: -73.9589),
            HeroSpot(id: "lm-nyc-apollo",          name: "The Apollo Theater",              lat: 40.8100, lng: -73.9500),
            HeroSpot(id: "lm-nyc-columbia",        name: "Columbia University",             lat: 40.8075, lng: -73.9626),
            HeroSpot(id: "lm-nyc-cathedral-sjd",   name: "Cathedral of St. John the Divine", lat: 40.8038, lng: -73.9618),
            HeroSpot(id: "lm-nyc-yankee-stadium",  name: "Yankee Stadium",                  lat: 40.8292, lng: -73.9262),
            HeroSpot(id: "lm-nyc-grand-concourse", name: "The Grand Concourse",             lat: 40.8270, lng: -73.9227),
            HeroSpot(id: "lm-nyc-bronx-zoo",       name: "The Bronx Zoo",                   lat: 40.8528, lng: -73.8810),
            HeroSpot(id: "lm-nyc-arthur-ave",      name: "Arthur Avenue",                   lat: 40.8547, lng: -73.8880),
            HeroSpot(id: "lm-nyc-grand-army-plz",  name: "Grand Army Plaza",                lat: 40.6743, lng: -73.9701),
            HeroSpot(id: "lm-nyc-brooklyn-museum", name: "Brooklyn Museum",                 lat: 40.6712, lng: -73.9630),
            HeroSpot(id: "lm-nyc-barclays",        name: "Barclays Center",                 lat: 40.6829, lng: -73.9759),
            HeroSpot(id: "lm-nyc-brooklyn-hts",    name: "Brooklyn Heights Promenade",      lat: 40.6962, lng: -73.9977),
            HeroSpot(id: "lm-nyc-coney-island",    name: "Coney Island Boardwalk",          lat: 40.5749, lng: -73.9785),
            HeroSpot(id: "lm-nyc-unisphere",       name: "The Unisphere",                   lat: 40.7466, lng: -73.8448),
            HeroSpot(id: "lm-nyc-citi-field",      name: "Citi Field",                      lat: 40.7564, lng: -73.8458),
            HeroSpot(id: "lm-nyc-flushing",        name: "Downtown Flushing",               lat: 40.7593, lng: -73.8300),
            HeroSpot(id: "lm-nyc-long-island-city",name: "Pepsi-Cola sign, Long Island City", lat: 40.7475, lng: -73.9576),
            HeroSpot(id: "lm-nyc-sttn-ferry",      name: "St. George Ferry Terminal",       lat: 40.6437, lng: -74.0736),
            HeroSpot(id: "lm-nyc-battery-park",    name: "Battery Park",                    lat: 40.7033, lng: -74.0170),
        ],
        "la": [
            HeroSpot(id: "lm-la-walk-of-fame",     name: "Hollywood Walk of Fame",          lat: 34.1016, lng: -118.3267),
            HeroSpot(id: "lm-la-chinese-theatre",  name: "TCL Chinese Theatre",             lat: 34.1022, lng: -118.3409),
            HeroSpot(id: "lm-la-capitol-records",  name: "Capitol Records Building",        lat: 34.1033, lng: -118.3259),
            HeroSpot(id: "lm-la-pantages",         name: "Hollywood Pantages Theatre",      lat: 34.1021, lng: -118.3250),
            HeroSpot(id: "lm-la-griffith",         name: "Griffith Observatory",            lat: 34.1184, lng: -118.3004),
            HeroSpot(id: "lm-la-hollywood-bowl",   name: "Hollywood Bowl",                  lat: 34.1122, lng: -118.3391),
            HeroSpot(id: "lm-la-sunset-strip",     name: "Sunset Strip",                    lat: 34.0907, lng: -118.3857),
            HeroSpot(id: "lm-la-rodeo-drive",      name: "Rodeo Drive",                     lat: 34.0676, lng: -118.4010),
            HeroSpot(id: "lm-la-beverly-hills-sign", name: "Beverly Hills sign",            lat: 34.0676, lng: -118.4146),
            HeroSpot(id: "lm-la-getty",            name: "The Getty Center",                lat: 34.0780, lng: -118.4741),
            HeroSpot(id: "lm-la-lacma",            name: "LACMA's Urban Light",             lat: 34.0630, lng: -118.3592),
            HeroSpot(id: "lm-la-farmers-market",   name: "The Original Farmers Market",     lat: 34.0717, lng: -118.3598),
            HeroSpot(id: "lm-la-la-brea",          name: "La Brea Tar Pits",                lat: 34.0629, lng: -118.3549),
            HeroSpot(id: "lm-la-walt-disney",      name: "Walt Disney Concert Hall",        lat: 34.0553, lng: -118.2498),
            HeroSpot(id: "lm-la-the-broad",        name: "The Broad",                       lat: 34.0545, lng: -118.2505),
            HeroSpot(id: "lm-la-city-hall",        name: "Los Angeles City Hall",           lat: 34.0537, lng: -118.2427),
            HeroSpot(id: "lm-la-grand-central-mkt", name: "Grand Central Market",           lat: 34.0508, lng: -118.2489),
            HeroSpot(id: "lm-la-bradbury",         name: "The Bradbury Building",           lat: 34.0507, lng: -118.2478),
            HeroSpot(id: "lm-la-union-station",    name: "Union Station",                   lat: 34.0560, lng: -118.2365),
            HeroSpot(id: "lm-la-olvera-st",        name: "Olvera Street",                   lat: 34.0576, lng: -118.2378),
            HeroSpot(id: "lm-la-chinatown",        name: "Chinatown's Central Plaza",       lat: 34.0636, lng: -118.2383),
            HeroSpot(id: "lm-la-little-tokyo",     name: "Little Tokyo",                    lat: 34.0503, lng: -118.2400),
            HeroSpot(id: "lm-la-arts-district",    name: "The Arts District",               lat: 34.0412, lng: -118.2340),
            HeroSpot(id: "lm-la-crypto-arena",     name: "Crypto.com Arena",                lat: 34.0430, lng: -118.2673),
            HeroSpot(id: "lm-la-la-live",          name: "L.A. Live",                       lat: 34.0448, lng: -118.2658),
            HeroSpot(id: "lm-la-coliseum",         name: "L.A. Memorial Coliseum",          lat: 34.0141, lng: -118.2879),
            HeroSpot(id: "lm-la-usc",              name: "USC",                             lat: 34.0205, lng: -118.2856),
            HeroSpot(id: "lm-la-exposition-park",  name: "Exposition Park Rose Garden",     lat: 34.0170, lng: -118.2887),
            HeroSpot(id: "lm-la-dodger-stadium",   name: "Dodger Stadium",                  lat: 34.0739, lng: -118.2400),
            HeroSpot(id: "lm-la-echo-park-lake",   name: "Echo Park Lake",                  lat: 34.0729, lng: -118.2608),
            HeroSpot(id: "lm-la-silver-lake-res",  name: "Silver Lake Reservoir",           lat: 34.0949, lng: -118.2658),
            HeroSpot(id: "lm-la-los-feliz",        name: "Vermont Ave, Los Feliz",          lat: 34.1062, lng: -118.2914),
            HeroSpot(id: "lm-la-koreatown",        name: "Wilshire Blvd, Koreatown",        lat: 34.0618, lng: -118.3006),
            HeroSpot(id: "lm-la-wiltern",          name: "The Wiltern",                     lat: 34.0617, lng: -118.3087),
            HeroSpot(id: "lm-la-macarthur-park",   name: "MacArthur Park",                  lat: 34.0579, lng: -118.2779),
            HeroSpot(id: "lm-la-santa-monica-pier", name: "Santa Monica Pier",              lat: 34.0100, lng: -118.4960),
            HeroSpot(id: "lm-la-third-st",         name: "Third Street Promenade",          lat: 34.0159, lng: -118.4960),
            HeroSpot(id: "lm-la-venice-boardwalk", name: "Venice Beach Boardwalk",          lat: 33.9850, lng: -118.4726),
            HeroSpot(id: "lm-la-venice-canals",    name: "Venice Canals",                   lat: 33.9848, lng: -118.4660),
            HeroSpot(id: "lm-la-abbot-kinney",     name: "Abbot Kinney Blvd",               lat: 33.9920, lng: -118.4700),
            HeroSpot(id: "lm-la-ucla",             name: "UCLA's Royce Hall",               lat: 34.0729, lng: -118.4422),
            HeroSpot(id: "lm-la-culver-city",      name: "Culver City's Culver Hotel",      lat: 34.0233, lng: -118.3957),
            HeroSpot(id: "lm-la-sofi",             name: "SoFi Stadium",                    lat: 33.9535, lng: -118.3392),
            HeroSpot(id: "lm-la-watts-towers",     name: "Watts Towers",                    lat: 33.9387, lng: -118.2413),
            HeroSpot(id: "lm-la-leimert-park",     name: "Leimert Park Village",            lat: 34.0047, lng: -118.3325),
            HeroSpot(id: "lm-la-highland-park",    name: "Figueroa St, Highland Park",      lat: 34.1110, lng: -118.1920),
            HeroSpot(id: "lm-la-greek-theatre",    name: "The Greek Theatre",               lat: 34.1197, lng: -118.2965),
            HeroSpot(id: "lm-la-universal",        name: "Universal CityWalk",              lat: 34.1364, lng: -118.3534),
            HeroSpot(id: "lm-la-el-capitan",       name: "El Capitan Theatre",              lat: 34.1016, lng: -118.3395),
            HeroSpot(id: "lm-la-pershing-sq",      name: "Pershing Square",                 lat: 34.0484, lng: -118.2533),
        ],
        "sf": [
            HeroSpot(id: "lm-sf-golden-gate",      name: "Golden Gate Bridge",              lat: 37.8078, lng: -122.4750),
            HeroSpot(id: "lm-sf-painted-ladies",   name: "The Painted Ladies",              lat: 37.7762, lng: -122.4328),
            HeroSpot(id: "lm-sf-lombard",          name: "Lombard Street",                  lat: 37.8021, lng: -122.4187),
            HeroSpot(id: "lm-sf-coit-tower",       name: "Coit Tower",                      lat: 37.8024, lng: -122.4058),
            HeroSpot(id: "lm-sf-ferry-building",   name: "Ferry Building",                  lat: 37.7955, lng: -122.3937),
            HeroSpot(id: "lm-sf-pier-39",          name: "Pier 39",                         lat: 37.8087, lng: -122.4098),
            HeroSpot(id: "lm-sf-fishermans-wharf", name: "Fisherman's Wharf",               lat: 37.8080, lng: -122.4177),
            HeroSpot(id: "lm-sf-ghirardelli",      name: "Ghirardelli Square",              lat: 37.8058, lng: -122.4228),
            HeroSpot(id: "lm-sf-palace-arts",      name: "Palace of Fine Arts",             lat: 37.8029, lng: -122.4484),
            HeroSpot(id: "lm-sf-chinatown-gate",   name: "Chinatown's Dragon Gate",         lat: 37.7906, lng: -122.4056),
            HeroSpot(id: "lm-sf-transamerica",     name: "Transamerica Pyramid",            lat: 37.7952, lng: -122.4028),
            HeroSpot(id: "lm-sf-union-sq",         name: "Union Square",                    lat: 37.7880, lng: -122.4075),
            HeroSpot(id: "lm-sf-cable-car-turn",   name: "Powell St cable car turnaround",  lat: 37.7847, lng: -122.4078),
            HeroSpot(id: "lm-sf-city-hall",        name: "San Francisco City Hall",         lat: 37.7793, lng: -122.4193),
            HeroSpot(id: "lm-sf-war-memorial",     name: "War Memorial Opera House",        lat: 37.7781, lng: -122.4211),
            HeroSpot(id: "lm-sf-asian-art",        name: "Asian Art Museum",                lat: 37.7802, lng: -122.4162),
            HeroSpot(id: "lm-sf-sfmoma",           name: "SFMOMA",                          lat: 37.7857, lng: -122.4011),
            HeroSpot(id: "lm-sf-yerba-buena",      name: "Yerba Buena Gardens",             lat: 37.7852, lng: -122.4028),
            HeroSpot(id: "lm-sf-salesforce-tower", name: "Salesforce Tower",                lat: 37.7897, lng: -122.3966),
            HeroSpot(id: "lm-sf-oracle-park",      name: "Oracle Park",                     lat: 37.7786, lng: -122.3893),
            HeroSpot(id: "lm-sf-chase-center",     name: "Chase Center",                    lat: 37.7680, lng: -122.3877),
            HeroSpot(id: "lm-sf-bay-bridge",       name: "Bay Bridge from the Embarcadero", lat: 37.7899, lng: -122.3890),
            HeroSpot(id: "lm-sf-haight-ashbury",   name: "Haight & Ashbury",                lat: 37.7700, lng: -122.4469),
            HeroSpot(id: "lm-sf-castro-theatre",   name: "The Castro Theatre",              lat: 37.7620, lng: -122.4348),
            HeroSpot(id: "lm-sf-mission-dolores",  name: "Mission Dolores",                 lat: 37.7644, lng: -122.4268),
            HeroSpot(id: "lm-sf-dolores-park",     name: "Dolores Park",                    lat: 37.7596, lng: -122.4269),
            HeroSpot(id: "lm-sf-balmy-alley",      name: "Balmy Alley murals",              lat: 37.7520, lng: -122.4124),
            HeroSpot(id: "lm-sf-valencia",         name: "Valencia Street",                 lat: 37.7610, lng: -122.4215),
            HeroSpot(id: "lm-sf-twin-peaks",       name: "Twin Peaks",                      lat: 37.7521, lng: -122.4474),
            HeroSpot(id: "lm-sf-sutro-tower",      name: "Sutro Tower",                     lat: 37.7552, lng: -122.4528),
            HeroSpot(id: "lm-sf-de-young",         name: "de Young Museum",                 lat: 37.7714, lng: -122.4686),
            HeroSpot(id: "lm-sf-cal-academy",      name: "California Academy of Sciences",  lat: 37.7699, lng: -122.4661),
            HeroSpot(id: "lm-sf-conservatory",     name: "Conservatory of Flowers",         lat: 37.7721, lng: -122.4600),
            HeroSpot(id: "lm-sf-ocean-beach",      name: "Ocean Beach",                     lat: 37.7694, lng: -122.5107),
            HeroSpot(id: "lm-sf-cliff-house",      name: "The Cliff House",                 lat: 37.7784, lng: -122.5139),
            HeroSpot(id: "lm-sf-legion-honor",     name: "Legion of Honor",                 lat: 37.7845, lng: -122.5008),
            HeroSpot(id: "lm-sf-grace-cathedral",  name: "Grace Cathedral",                 lat: 37.7919, lng: -122.4131),
            HeroSpot(id: "lm-sf-fairmont",         name: "The Fairmont, Nob Hill",          lat: 37.7924, lng: -122.4104),
            HeroSpot(id: "lm-sf-alamo-square",     name: "Alamo Square",                    lat: 37.7766, lng: -122.4345),
            HeroSpot(id: "lm-sf-japantown",        name: "Japantown Peace Pagoda",          lat: 37.7853, lng: -122.4298),
            HeroSpot(id: "lm-sf-fillmore",         name: "The Fillmore",                    lat: 37.7840, lng: -122.4331),
            HeroSpot(id: "lm-sf-north-beach",      name: "Columbus Ave, North Beach",       lat: 37.7990, lng: -122.4079),
            HeroSpot(id: "lm-sf-city-lights",      name: "City Lights Bookstore",           lat: 37.7976, lng: -122.4066),
            HeroSpot(id: "lm-sf-exploratorium",    name: "The Exploratorium",               lat: 37.8016, lng: -122.3975),
            HeroSpot(id: "lm-sf-crissy-field",     name: "Crissy Field",                    lat: 37.8039, lng: -122.4644),
            HeroSpot(id: "lm-sf-presidio",         name: "The Presidio",                    lat: 37.7989, lng: -122.4662),
            HeroSpot(id: "lm-sf-fort-mason",       name: "Fort Mason",                      lat: 37.8063, lng: -122.4309),
            HeroSpot(id: "lm-sf-hayes-valley",     name: "Hayes Valley",                    lat: 37.7762, lng: -122.4245),
            HeroSpot(id: "lm-sf-embarcadero-ctr",  name: "Embarcadero Center",              lat: 37.7946, lng: -122.3990),
            HeroSpot(id: "lm-sf-market-st",        name: "Market Street",                   lat: 37.7880, lng: -122.4020),
        ],
        "dc": [
            HeroSpot(id: "lm-dc-capitol",          name: "U.S. Capitol",                    lat: 38.8893, lng: -77.0090),
            HeroSpot(id: "lm-dc-white-house",      name: "The White House",                 lat: 38.8990, lng: -77.0365),
            HeroSpot(id: "lm-dc-washington-mon",   name: "Washington Monument",             lat: 38.8895, lng: -77.0325),
            HeroSpot(id: "lm-dc-lincoln-mem",      name: "Lincoln Memorial",                lat: 38.8893, lng: -77.0492),
            HeroSpot(id: "lm-dc-jefferson-mem",    name: "Jefferson Memorial",              lat: 38.8814, lng: -77.0365),
            HeroSpot(id: "lm-dc-mlk-mem",          name: "Martin Luther King Jr. Memorial", lat: 38.8862, lng: -77.0442),
            HeroSpot(id: "lm-dc-library-congress", name: "Library of Congress",             lat: 38.8887, lng: -77.0047),
            HeroSpot(id: "lm-dc-supreme-court",    name: "Supreme Court",                   lat: 38.8906, lng: -77.0045),
            HeroSpot(id: "lm-dc-union-station",    name: "Union Station",                   lat: 38.8973, lng: -77.0063),
            HeroSpot(id: "lm-dc-air-space",        name: "National Air and Space Museum",   lat: 38.8880, lng: -77.0198),
            HeroSpot(id: "lm-dc-natural-history",  name: "National Museum of Natural History", lat: 38.8913, lng: -77.0261),
            HeroSpot(id: "lm-dc-nmaahc",           name: "National Museum of African American History", lat: 38.8910, lng: -77.0327),
            HeroSpot(id: "lm-dc-smithsonian",      name: "Smithsonian Castle",              lat: 38.8888, lng: -77.0260),
            HeroSpot(id: "lm-dc-national-gallery", name: "National Gallery of Art",         lat: 38.8913, lng: -77.0199),
            HeroSpot(id: "lm-dc-archives",         name: "National Archives",               lat: 38.8927, lng: -77.0230),
            HeroSpot(id: "lm-dc-ford-theatre",     name: "Ford's Theatre",                  lat: 38.8967, lng: -77.0257),
            HeroSpot(id: "lm-dc-chinatown-arch",   name: "Chinatown Friendship Archway",    lat: 38.9002, lng: -77.0219),
            HeroSpot(id: "lm-dc-capital-one-arena", name: "Capital One Arena",              lat: 38.8981, lng: -77.0209),
            HeroSpot(id: "lm-dc-portrait-gallery", name: "National Portrait Gallery",       lat: 38.8977, lng: -77.0230),
            HeroSpot(id: "lm-dc-treasury",         name: "Treasury Building",               lat: 38.8981, lng: -77.0341),
            HeroSpot(id: "lm-dc-eisenhower",       name: "Eisenhower Executive Office Building", lat: 38.8976, lng: -77.0390),
            HeroSpot(id: "lm-dc-lafayette",        name: "Lafayette Square",                lat: 38.8995, lng: -77.0366),
            HeroSpot(id: "lm-dc-kennedy-center",   name: "The Kennedy Center",              lat: 38.8957, lng: -77.0559),
            HeroSpot(id: "lm-dc-watergate",        name: "The Watergate",                   lat: 38.8993, lng: -77.0548),
            HeroSpot(id: "lm-dc-georgetown-m-st",  name: "M Street, Georgetown",            lat: 38.9050, lng: -77.0630),
            HeroSpot(id: "lm-dc-georgetown-univ",  name: "Georgetown University",           lat: 38.9076, lng: -77.0723),
            HeroSpot(id: "lm-dc-exorcist-steps",   name: "The Exorcist Steps",              lat: 38.9055, lng: -77.0702),
            HeroSpot(id: "lm-dc-dupont-circle",    name: "Dupont Circle",                   lat: 38.9096, lng: -77.0434),
            HeroSpot(id: "lm-dc-embassy-row",      name: "Embassy Row",                     lat: 38.9136, lng: -77.0508),
            HeroSpot(id: "lm-dc-national-cathedral", name: "Washington National Cathedral", lat: 38.9306, lng: -77.0708),
            HeroSpot(id: "lm-dc-national-zoo",     name: "National Zoo",                    lat: 38.9296, lng: -77.0498),
            HeroSpot(id: "lm-dc-adams-morgan",     name: "18th Street, Adams Morgan",       lat: 38.9215, lng: -77.0422),
            HeroSpot(id: "lm-dc-u-street",         name: "U Street Corridor",               lat: 38.9170, lng: -77.0290),
            HeroSpot(id: "lm-dc-bens-chili",       name: "Ben's Chili Bowl",                lat: 38.9170, lng: -77.0287),
            HeroSpot(id: "lm-dc-howard-theatre",   name: "The Howard Theatre",              lat: 38.9152, lng: -77.0214),
            HeroSpot(id: "lm-dc-howard-univ",      name: "Howard University",               lat: 38.9227, lng: -77.0194),
            HeroSpot(id: "lm-dc-columbia-heights", name: "Columbia Heights",                lat: 38.9287, lng: -77.0324),
            HeroSpot(id: "lm-dc-eastern-market",   name: "Eastern Market",                  lat: 38.8866, lng: -76.9962),
            HeroSpot(id: "lm-dc-barracks-row",     name: "Barracks Row",                    lat: 38.8810, lng: -76.9953),
            HeroSpot(id: "lm-dc-navy-yard",        name: "The Yards Park, Navy Yard",       lat: 38.8737, lng: -77.0015),
            HeroSpot(id: "lm-dc-nationals-park",   name: "Nationals Park",                  lat: 38.8730, lng: -77.0074),
            HeroSpot(id: "lm-dc-audi-field",       name: "Audi Field",                      lat: 38.8686, lng: -77.0128),
            HeroSpot(id: "lm-dc-wharf",            name: "The Wharf",                       lat: 38.8790, lng: -77.0240),
            HeroSpot(id: "lm-dc-h-street",         name: "H Street NE",                     lat: 38.9001, lng: -76.9940),
            HeroSpot(id: "lm-dc-anacostia",        name: "Frederick Douglass House, Anacostia", lat: 38.8634, lng: -76.9852),
            HeroSpot(id: "lm-dc-arboretum",        name: "National Arboretum",              lat: 38.9127, lng: -76.9707),
            HeroSpot(id: "lm-dc-shaw",             name: "Shaw's 7th Street",               lat: 38.9124, lng: -77.0219),
            HeroSpot(id: "lm-dc-logan-circle",     name: "Logan Circle",                    lat: 38.9096, lng: -77.0297),
            HeroSpot(id: "lm-dc-woodley-park",     name: "Connecticut Ave, Woodley Park",   lat: 38.9249, lng: -77.0525),
            HeroSpot(id: "lm-dc-petworth",         name: "Georgia Ave, Petworth",           lat: 38.9410, lng: -77.0240),
        ],
    ]
}
